export const meta = {
  name: 'pythiagex-4-0-independiente',
  description: 'PythiaGex 4.0 independiente y autocontenida: clon de la 3.0 + familia (29 series de la vista previa) + TQQQ x3 + descarga propia de CBOE + UI de la 4.0, en C#, con paridad contra Python y revision adversarial',
  phases: [
    { title: 'Entender', detail: 'fuentes de datos, mapa de la 3.0, cuenta de la vista previa y TQQQ' },
    { title: 'Disenar', detail: 'diseno del 4.0 unico y autocontenido' },
    { title: 'Contratos', detail: 'interfaces y propiedad de archivos para construir en paralelo' },
    { title: 'Construir', detail: '8 constructores en paralelo: clon, descargador CBOE, familia NQ/NDX/QQQ/FAM, TQQQ, pantalla' },
    { title: 'Integrar', detail: 'unir modulos, compilar, correr arneses' },
    { title: 'Verificar', detail: 'paridad numerica y revision de ATAS/hilos/protocolo' },
    { title: 'Arreglar', detail: 'aplicar lo confirmado y re-medir' },
  ],
}

const RAIZ = 'C:/Users/wmx_7/OneDrive/Escritorio/ATAS nada/PythiaGex'
const REGLAS = `
REGLAS DURAS (proyecto del operador, ver CLAUDE.md):
- NO instalar nada en ATAS, NO tocar ATAS ni reiniciarlo, NO copiar DLL a %APPDATA%/ATAS/Indicators. El instalador lo corre el agente principal.
- NO modificar atas/PythiaGexTres (3.0), atas/PythiaGexDos (2.0) ni atas/PythiaGexNiveles (clasica): solo LEER y COPIAR.
- NO tocar motor.py, fuentes.py, servir.py, ni herramientas/cboe_local.py. Para PROBAR usar archivos ya guardados; como mucho UNA bajada de prueba por ticker del endpoint de CBOE con gzip (para validar el descargador en C#), nunca rafagas.
- Python a prioridad BELOW_NORMAL (SetPriorityClass 0x4000) y con -I; el mercado esta abierto y ATAS corre: nada pesado en paralelo.
- Protocolo: todo nivel con fuente y edad; si el dato tiene mas de 30 min, la edad va ANTES del numero; nada de direccion ni rentabilidad.
- ATAS guarda los ajustes por NOMBRE de propiedad en el workspace: para cambiar un default guardado hay que renombrar la propiedad.
- ATAS: IndicatorCandle.Time viene en UTC con Kind=Unspecified (medido hoy): usar ticks crudos, nunca ToUniversalTime. El ChartArea es mas alto que lo visible (lo anclado al fondo cae detras del eje de tiempo). Las pestañas ocultas no reciben OnCalculate. ATAS se traga las excepciones: try/catch con log propio.
- Compilar: dotnet build -c Release -o bin/Release (net10.0-windows, referencias de ATAS con Private=false; ver atas/PythiaGexTres/PythiaGexTres.csproj y la memoria compilar-indicadores-atas).
Raiz: ${RAIZ}`

const CONTEXTO = `
CONTEXTO: el operador (MNQ, ATAS 8.0.15 + Rithmic) pidio UN SOLO indicador independiente ("debe ser independiente siempre; o modificas la 3.0 o
creas el 4.0 nuevo independiente; quiero uno solo"). La 4.0 actual (atas/PythiaGexCuatro: FamiliaCuatro.cs + DatosCuatro.cs, 4.0.6) es solo un
VISOR: lee profundidad/pagina/preview_datos/preview_niveles.json (de laboratorio/tres/auditoria_0810/preview_niveles.py, que importa
backtest_familia.py) y tqqq_vivo.json (de laboratorio/tres/tqqq/tqqq_vivo.py); esos generadores dependen de la 3.0 (cinta del MNQ en
profundidad/estado/cinta y libro viva3 de NQ en %APPDATA%/ATAS/PythiaGex3/viva). Cuando el operador cerro la pestaña de la 3.0, la 4.0 quedo en blanco.
DECISION: la 4.0 nueva = COPIA de la 3.0 (atas/PythiaGexTres, VERSION 3.6.9: libro NQ por Rithmic OptionsApi, cinta, capas NDX/QQQ) renombrada
(namespace/clases/DisplayName "PythiaGex 4.0 - Gamma Familia", DLL PythiaGexCuatro.dll, datos en %APPDATA%/ATAS/PythiaGex4, logs pythiagex4-*),
MAS un modulo "Familia" en C# que calcula las MISMAS series que la vista previa (29 series: NQ/NDX/QQQ muros y majors por vol y OI, familia sumada,
zero estandar, cruces, confluencia, lo que dibujo la 3.0 por libro, y TQQQ x3) con la misma cuenta (correcciones C1..C10 de backtest_familia.py;
TQQQ: NQ = s*K + c, s = cierreNDX/(3*cierreTQQQ) del dia anterior, c = mediana robusta de las ultimas 24 muestras MNQ(sello CBOE - 900 s) - s*spot en
rueda), MAS la UI de la 4.0.6 (etiquetas chicas pegadas al eje con "+N", pestaña desplegable que arranca cerrada con fuentes/edades/detalle, doble
eje elegible Ninguno/NDX/QQQ/TQQQ con la conversion de sus rayas, sin sombreado, control de vencimiento, una casilla bool por serie con defaults =
MAJORS_QQQ_oi, MUROS_NQ_oi, MUROS_NDX_vol, MUROS_QQQ_oi, FAM_MUROS_oi, ZEST_QQQ_vol, TRES_NDX, T_MUROS_oi).
REGLA NUEVA DEL OPERADOR (08-10 19:2x, textual: "no entiendo por que no lo podemos calcular todo aca adentro si de ATAS y Rithmic sale todo...
resolvelo, se profesional y que este todo dentro del indicador"): CERO dependencias externas. Ni generadores Python, ni cboe_local, ni archivos
escritos por otros programas. Lo de CME (futuro MNQ/NQ y opciones de NQ) sale de ATAS/Rithmic como en la 3.0. Las opciones de NDX (indice, CBOE)
y de QQQ/TQQQ (OPRA) NO las transmite Rithmic (es un feed de futuros): (a) primero averiguar si ATAS las puede dar por su API (IOptionsDataProvider /
OptionsSubscriptionService / instrumentos de opciones de acciones o indices en ATAS con OI, volumen e IV) y con que proveedor; (b) si no, la propia
4.0 baja la cadena de CBOE (los mismos endpoints publicos cdn.cboe.com/api/global/delayed_quotes/options/<TICKER>.json que usa
herramientas/cboe_local.py, con _NDX/NDX segun corresponda), en un hilo de fondo de baja prioridad, con HttpClient + gzip
(AutomaticDecompression) y lectura en trozos con pausas (regla del proyecto: toda descarga comprimida y sin rafagas, como pythiagex.fuentes.bajar;
las rafagas coincidian con cortes de Rithmic), un ticker por vez y la misma cadencia que cboe_local, guardando su propio archivo en
%APPDATA%/ATAS/PythiaGex4 (ultima y historico del dia, para la estela y para reanclar la noche). La 3.0 y la 4.0 tienen que poder correr a la vez
sin pisarse archivos ni cupos.`

phase('Entender')
const [mapaFuentes, mapa30, mapaPrev, mapaTq] = await parallel([
  () => agent(`${REGLAS}\n${CONTEXTO}\nTAREA: FUENTES DE DATOS SIN PROGRAMAS EXTERNOS. (1) Averiguar con evidencia si ATAS 8.0.15 puede dar opciones de QQQ, TQQQ y NDX (cadena con OI, volumen, IV/griegas) por su API o por algun conector del operador (Rithmic lucid; hay filas dxFeed, ATAS Sim, etc. en Connections): leer el volcado de la API por reflexion (atas/_api y sus salidas), la memoria atas-8-0-15-api-opciones y cadena-es-en-vivo-rithmic, el codigo de la 3.0 que suscribe opciones (CadenaApi.cs, PuenteRithmic si existe) y los logs de ATAS (%APPDATA%/ATAS/Logs: buscar 'QQQ', 'OPRA', 'options'); NO abrir ATAS ni conectar nada. Concluir SI/NO con la evidencia. (2) Especificar el port a C# del descargador de CBOE: leer herramientas/cboe_local.py y pythiagex/fuentes.py (solo leer): endpoints exactos por ticker, cabeceras, gzip, tamaños, lectura en trozos y pausas, cadencia, reintentos, deteccion de cadena congelada, campos que usan la 3.0 y la vista previa (spot, ts/sello, prev_day_close, open_interest, volume, iv, gamma, last_trade_time), atraso de ~900 s, filtro flaco (+-5 %, <=8 dias) y formato a guardar. Devolver la especificacion completa.`, { label: 'fuentes de datos', phase: 'Entender' }),
  () => agent(`${REGLAS}\n${CONTEXTO}\nTAREA: mapear la 3.0 (atas/PythiaGexTres, solo lectura) para clonarla. Entregar: lista de archivos .cs y que hace cada uno; donde se arma el libro de NQ (CadenaApi, GammaHoyNucleo, Feed), la cinta (GammaHoyTresCinta), las capas NDX/QQQ (GammaHoyTresCapas: base NDX, razon QQQ, de donde lee cboe-local: ESO hay que reemplazarlo por la descarga propia), la memoria/estela, el render (Pintar, Rotulos), timers, locks; TODO nombre que hay que cambiar para que un clon conviva con la 3.0 (clases, DisplayName, Category, carpetas de datos Registro.CarpetaDatos, nombres de log, archivos que escribe: cinta, viva3, estela, centinela, indicador.json, pulsos, recuadro...), y cualquier recurso compartido (suscripciones de opciones: cupo 200/512 por instancia, ver memoria atas-8-0-15-api-opciones) que dos instancias pelearian. Revisar si existe un script de clonado (herramientas/clonar_2_0.py, clonar_*). Devolver un informe concreto con rutas y lineas.`, { label: 'mapa 3.0', phase: 'Entender' }),
  () => agent(`${REGLAS}\n${CONTEXTO}\nTAREA: especificar EXACTAMENTE la cuenta de cada una de las 29 series de la vista previa para portarla a C#: leer laboratorio/tres/auditoria_0810/preview_niveles.py y backtest_familia.py (y lo que importen: tres/velas, extremos_rebote, nucleo, libros). Para cada serie id (MUROS_NQ_vol, MUROS_NQ_oi, MAJORS_*, FAM_MUROS_*, CONF_vol, ZEST_*, ZTP_*, TRES_*): entradas (que libro, que horizonte de vencimientos, vol u OI, radio en pts o %), formula (gamma BS o Black-76, multiplicador por libro C1, signo calls+/puts-, escala S^2*0.01), seleccion (strike exacto, lado, islas C3, sin histeresis C4, zero estandar C5 = repreciado?), conversion a precio de NQ (NQ: corrimiento; NDX: base sincronizada C7 con su regla de noche; QQQ: razon sincronizada C8), vigencia (C2 OI de NQ con fecha y salto de OI; C9 cadena congelada valida hasta 13:30 UTC; C10 vencido excluido, horizonte Hoy), con que frecuencia y en que clave de tiempo se guarda (velas m2), banda, colores, y que es TRES_* (estela de la 3.0). Senalar lo que la 3.0 YA calcula igual (comparar con atas/PythiaGexTres: GammaHoyNucleo, GammaHoyTresCapas, GammaHoyTresMajorOi) y lo que habria que escribir nuevo. Incluir los parametros numericos exactos (tasa, piso de dias, radios). Devolver la especificacion completa, sin resumir formulas.`, { label: 'cuenta vista previa', phase: 'Entender' }),
  () => agent(`${REGLAS}\n${CONTEXTO}\nTAREA: especificar TQQQ para portarlo a C#: leer laboratorio/tres/tqqq/tqqq_vivo.py, tq_comun.py, t02_conversion.py (y los resultados salidas/*.md, t07/t08) y el formato de la cadena de TQQQ de CBOE (crudo en laboratorio/tres/tqqq/crudo/ y el archivo de cboe-local cadena-TQQQ-<dia>.jsonl.gz: campos, spot, prev_day_close, ts/sello, filas). Especificar: perfil del vencimiento mas cercano (BS, tasa, piso), las 5 series (T_DOMS_vol, T_MUROS_vol, T_MUROS_oi, T_ZERO_oi, T_DOMS_raz), el calculo de s (cierres del dia anterior: prev_day_close de la cadena completa y el cierre de NDX) y de c (muestras sincronizadas con la cinta del MNQ, 900 s, mediana robusta de 24, solo rueda y spot vivo), comportamiento de noche (cadena congelada: reanclar s y c al cierre de hoy, con la formula), y como tener la cinta del MNQ en C# en vivo dentro del indicador (la 3.0 ya la tiene en memoria?). Devolver especificacion completa.`, { label: 'TQQQ', phase: 'Entender' }),
])

phase('Disenar')
const diseno = args.diseno
log('diseno y contratos: los hizo el agente principal (args)')

// ===================== desde aca, construccion EN PARALELO (pedido del operador: "pone todos tus recursos, no quiero estar toda la noche") =====
phase('Contratos')
const contratos = args.contratos

phase('Construir')
const BASE = `${REGLAS}\n${CONTEXTO}\nDISENO:\n${diseno}\n--- ESPECIFICACION DE LA CUENTA (informe 'cuenta vista previa') ---\n${mapaPrev}\n--- TQQQ ---\n${mapaTq}\n--- FUENTES Y DESCARGADOR ---\n${mapaFuentes}\n--- MAPA DE LA 3.0 ---\n${mapa30}\nCONTRATOS (respetarlos al pie de la letra; leer tambien ${RAIZ}/atas/PythiaGexCuatro/_contratos/):\n${contratos}\n
Trabajas EN PARALELO con otros 7 constructores: SOLO escribis en tus archivos (ver PLAN_PARALELO.md). Si necesitas algo de otro modulo, usa la interfaz
del contrato y un doble de prueba. Compila tu parte sola (csproj de prueba propio) y deja pruebas que se puedan re-correr. NO instalar.
REFERENCIA YA GENERADA por el agente principal (NO recalcular la cuenta pesada en Python): ${RAIZ}/atas/_test_cuatro_paridad/referencia/ref-2026-10-07.json y ref-2026-10-08.json = preview_niveles.Motor(vivo=False).historico() sobre la sesion completa: niv[clave de minuto (ns 60e9)][serie] = [[precio NQ, etiqueta, GEX M USD]], tres (capas de la 3.0), salida (historia m2 y actuales). Si todavia no existen, esperar unos minutos (las genera generar_referencia.py en esa carpeta). Para TQQQ la referencia es laboratorio/tres/tqqq/salidas (t02/t04/t07/t08, niveles_dia.pkl) y tqqq_vivo.py.`
const [b1, b2, b3a, b3b, b3c, b3d, b4, b5] = await parallel([
  () => agent(`${BASE}\nSOS B1 (TERMINAR EL CLON + ADAPTADORES): el agente principal ya clono con herramientas/clonar_4_0.py (leer el script). Escribir ademas AdaptadoresFamilia.cs en la raiz del proyecto con ILibroNq (fotos por minuto del libro de NQ sacadas de CadenaApi/Viva3 del clon, con historia de la sesion y siembra al arrancar desde PythiaGex4/viva) e ICinta (ticks de la cinta del clon en memoria + velas m2 + historia de dias previos desde PythiaGex4/cinta o, si no hay, desde las velas del grafico), segun Contratos.cs. Revisar el clon y terminar: carpeta de la cinta propia (Cinta3Carpeta y el fallback de CintaCarpeta -> %APPDATA%/ATAS/PythiaGex4/cinta), nombre del hilo, Estado3Ruta propia o pulso apagado, textos "PythiaGex 3.0", relleno de cinta apagado por defecto (propiedad con nombre NUEVO), desfase de 15-20 s en el primer armado de la cadena, RETRASO_CBOE_S 900, apagar por defecto lo propio de la 3.0 (dominantes, tunel, zero, capas, recuadro libro, cabecera, formulas) con nombres de propiedad NUEVOS, y dejar marcas // GANCHO-4.1 donde se conectan el descargador (reemplazo de CarpetaCboeLocal, NUBE y base-rueda de la clasica en Capas.cs), la familia, TQQQ y la pantalla. Compilar el clon solo. Devolver: cambios, ganchos (archivo:linea), build.`, { label: 'B1 clon', phase: 'Construir' }),
  () => agent(`${BASE}\nSOS B2 (DESCARGADOR CBOE en C#): implementar IFuenteCboe en _modulos/cboe/: hilo de fondo de baja prioridad, HttpClient con AutomaticDecompression gzip y Accept-Encoding gzip, User-Agent, lectura en trozos de 256 KB con pausa de 50 ms, un ticker por vez (_NDX, QQQ, TQQQ), cadencia 75 s entre 13:20 y 20:10 UTC de lunes a viernes y 300 s fuera, no guardar si el timestamp de CBOE no cambio, reintentos con espera, armado de la cadena como pythiagex/cadena_atas.py construir (5 %, 14 dias, filtros, ultimo_trade, filas [K, vi, oi_c, oi_p, iv_c, iv_p, vol_c, vol_p], linea flaca 8 dias), base_cruda por forwards como pythiagex/base.py medir, edad = ts - 900 s, guardado propio en %APPDATA%/ATAS/PythiaGex4 (ultima-<raiz>.json y cadena-<raiz>-<dia>.jsonl.gz) y lectura del historico del dia al arrancar; exponer prev_day_close/close del json si existe. Prueba: consola con UNA bajada por ticker comparando el armado contra pythiagex/cadena_atas.py (Python, solo lectura) sobre el mismo json. Devolver: archivos, build, prueba (tamaños, tiempos, diferencias).`, { label: 'B2 descargador', phase: 'Construir' }),
  () => agent(`${BASE}\nSOS B3a (FAMILIA NQ + CODIGO COMUN): escribir _modulos/familia/comun/* (gamma BS y Black-76, perfil por strike por lado vol/OI, seleccion de muros/majors/zero estandar/cruces sin islas, claves m2 UTC) y _modulos/familia/nq/* con MUROS_NQ_vol, MUROS_NQ_oi, MAJORS_NQ_vol, MAJORS_NQ_oi, ZEST_NQ_vol, ZEST_NQ_oi, ZTP_NQ_vol EXACTAMENTE como la especificacion (C1 multiplicador 20, C2 OI de NQ con fecha y salto, C3, C4, C5, C6, corrimiento futuro-MNQ). Arnes atas/_test_cuatro_paridad/nq/ sobre 07-10 y 08-10 (viva3 de PythiaGex3 y cinta archivadas como entrada) contra preview_niveles.py/backtest_familia. Iterar hasta paridad o explicar cada diferencia. Publicar el codigo comun TEMPRANO (los otros lo usan). Devolver: archivos, build, paridad por serie.`, { label: 'B3a familia NQ', phase: 'Construir' }),
  () => agent(`${BASE}\nSOS B3b (FAMILIA NDX): _modulos/familia/ndx/* con MUROS_NDX_vol, MUROS_NDX_oi, MAJORS_NDX_vol, MAJORS_NDX_oi, ZEST_NDX_vol, ZTP_NDX_vol y la base NDX sincronizada C7 (reusar atas/_propuesta_3_7/PythiaGexTres/Conversion37.cs, que porta backtest_familia: retraso 900, VIVO 600, MIN_DIA 5, MIN_RUEDA 20, ventana 24, carry de noche, estado persistido en PythiaGex4), cadena congelada valida hasta 13:30 UTC, vencido excluido. Usar el codigo comun de B3a (si todavia no esta, un doble minimo y despues alinear). Arnes atas/_test_cuatro_paridad/ndx/ sobre 07-10 y 08-10 (cboe-local archivado de NQ=NDX y cinta como entrada) contra preview_niveles.py. Devolver: archivos, build, paridad por serie.`, { label: 'B3b familia NDX', phase: 'Construir' }),
  () => agent(`${BASE}\nSOS B3c (FAMILIA QQQ): _modulos/familia/qqq/* con MUROS_QQQ_vol, MUROS_QQQ_oi, MAJORS_QQQ_vol, MAJORS_QQQ_oi, ZEST_QQQ_vol y la razon QQQ sincronizada C8 (Conversion37.cs), banda +-20, cadena congelada hasta 13:30 UTC, vencido excluido. Usar el codigo comun de B3a. Arnes atas/_test_cuatro_paridad/qqq/ sobre 07-10 y 08-10 contra preview_niveles.py. Devolver: archivos, build, paridad por serie.`, { label: 'B3c familia QQQ', phase: 'Construir' }),
  () => agent(`${BASE}\nSOS B3d (FAMILIA SUMADA, CONFLUENCIA, 3.0 y ALMACEN): _modulos/familia/fam/* con FAM_MUROS_vol, FAM_MUROS_oi (familia sumada con multiplicadores C1), CONF_vol, TRES_NQ/TRES_NDX/TRES_QQQ (lo que dibuja el propio indicador en sus capas: definir de donde salen en el clon), y el ALMACEN de historia por vela m2 (mismas claves que la vista previa) con siembra al arrancar desde su propio archivo en PythiaGex4 y desde el historico del descargador (para que al abrir ATAS la estela de la sesion este completa). Arnes atas/_test_cuatro_paridad/fam/ contra preview_niveles.py. Devolver: archivos, build, paridad.`, { label: 'B3d familia FAM', phase: 'Construir' }),
  () => agent(`${BASE}\nSOS B4 (TQQQ): implementar ICalculoTqqq en _modulos/tqqq/: perfil del vencimiento mas cercano (BS), las 5 series T_*, s = cierre NDX / (3 x cierre TQQQ) de la sesion anterior (del historico propio del descargador o prev_day_close del json), c = mediana robusta de 24 muestras MNQ(sello-900 s) - s*spot en rueda con spot vivo (anillo de precios del MNQ en memoria desde la cinta del indicador), reanclaje de noche al cierre de hoy, razon de comparacion (T_DOMS_raz). Arnes atas/_test_cuatro_paridad/tqqq/ contra tqqq_vivo.py y t02 sobre 08-10 (s 124,213; c ~21.009; 82 -> 31.195). Devolver: archivos, build, paridad con numeros.`, { label: 'B4 TQQQ', phase: 'Construir' }),
  () => agent(`${BASE}\nSOS B5 (PANTALLA): implementar IPantallaFamilia en _modulos/pantalla/ portando de atas/PythiaGexCuatro/_visor_4_0_6/FamiliaCuatro.cs (4.0.6) TODO lo que el operador aprobo: rayitas por vela con hora por ticks, etiquetas chicas pegadas al eje con "+N" y edad arriba de la columna (DATO DE HACE antes de los numeros), pestaña desplegable que arranca cerrada (ProcessMouseClick, margen 56, Recuadro abierto), doble eje elegible Ninguno/NDX/QQQ/TQQQ con la conversion de sus rayas (GetYByPrice por marca, paso automatico), control de vencimiento, sin sombreado, una casilla por serie con defaults del operador (proponer los nombres de propiedad: conviene reusar S_<id>, Eje4Libro, Estela4, Rotulos4, Cabecera4, Letra4, MargenSup4 para que ATAS conserve lo que el operador ya eligio). Que funcione sobre la foto del contrato (no json). Prueba: compilar contra ATAS y un doble de foto. Devolver: archivos, build, lista de propiedades y defaults.`, { label: 'B5 pantalla', phase: 'Construir' }),
])

return { b1, b2, b3a, b3b, b3c, b3d, b4, b5 }
